repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.1.8
  hooks:
    - id: ruff
      args: [--fix,--exit-non-zero-on-fix,--preview,--diff]
    - id: ruff-format
      args: [--preview,--diff]
- repo: https://github.com/pdm-project/pdm
  rev: 2.12.4 # a PDM release exposing the hook
  hooks:
    - id: pdm-lock-check
      always_run: true