repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.11.13
  hooks:
    - id: ruff
      args: [--fix,--exit-non-zero-on-fix,--preview,--diff]
    - id: ruff-format
      args: [--preview,--diff]
- repo: https://github.com/pdm-project/pdm
  rev: 2.24.2 # a PDM release exposing the hook
  hooks:
    - id: pdm-lock-check
      always_run: true
      config-setting: use_uv=true
    - id: pdm-sync
      additional_dependencies:
        - keyring