version: "3.10"

networks:
  shared: { }

services:
  api:
    restart: no
    image: tg_chat_parser:latest
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    depends_on:
      postgres:
        condition: service_healthy
      rabbit:
        condition: service_healthy
    networks: [ shared ]
    env_file:
      - .env
    environment:
      - PG_DSN=postgresql+asyncpg://postgres:postgres@postgres:5432/app
      - RABBIT_DSN=amqp://rabbit:5672
    secrets:
      - TG_API_ID
      - TG_API_HASH
    entrypoint: bash -c "python -m alembic upgrade head && python -m chat_parser"
  postgres:
    image: postgres:15-alpine
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d app" ]
      interval: 2s
      timeout: 1s
      retries: 5
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks: [ shared ]
    ports:
      - "52326:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  rabbit:
    image: rabbitmq:3.13-management
    networks: [ shared ]
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 2s
      timeout: 1s
      retries: 5
    ports:
      - "15672:15672"
      - "56722:5672"

secrets:
   TG_API_ID:
     file: .secrets/TG_API_ID
   TG_API_HASH:
     file: .secrets/TG_API_HASH

volumes:
  postgres-data: