version: "3.10"

networks:
  shared: { }

services:
  api:
    restart: no
    image: tg_chat_parser:latest
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    depends_on:
      postgres:
        condition: service_healthy
    networks: [ shared ]
    env_file:
      - .env
    secrets:
      - PG_DSN
      - TG_API_ID
      - TG_API_HASH
  postgres:
    image: postgres:15-alpine
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d app" ]
      interval: 2s
      timeout: 1s
      retries: 5
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks: [ shared ]
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

secrets:
   PG_DSN:
     file: .secrets/PG_DSN
   TG_API_ID:
     file: .secrets/TG_API_ID
   TG_API_HASH:
     file: .secrets/TG_API_HASH

volumes:
  postgres-data: