"""init

Revision ID: 56331c0034b5
Revises:
Create Date: 2025-07-29 01:56:43.724138

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "56331c0034b5"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "entities",
        sa.Column("entity_id", sa.BigInteger(), nullable=False),
        sa.Column("entity_name", sa.String(), nullable=False),
        sa.Column("entity_url", sa.String(), nullable=False),
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="crawler",
    )
    op.create_table(
        "sessions",
        sa.Column("session", sa.String(), nullable=False),
        sa.Column("api_id", sa.BigInteger(), nullable=False),
        sa.Column("api_hash", sa.String(), nullable=False),
        sa.Column("tel", sa.String(), nullable=False),
        sa.Column("proxy", sa.String(), nullable=False),
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="crawler",
    )
    op.create_table(
        "channel_metadata",
        sa.Column("entity_id", sa.BigInteger(), nullable=False),
        sa.Column("from_message_id", sa.BigInteger(), nullable=False),
        sa.Column("to_message_id", sa.BigInteger(), nullable=False),
        sa.Column("from_datetime", sa.DateTime(), nullable=False),
        sa.Column("to_datetime", sa.DateTime(), nullable=False),
        sa.Column("messages_count", sa.Integer(), nullable=False),
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["entity_id"], ["crawler.entities.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "entity_id",
            "from_message_id",
            "to_message_id",
            name="uix_entity_message_range",
        ),
        schema="crawler",
    )
    op.create_index(
        "ix_entity_datetime_range",
        "channel_metadata",
        ["entity_id", "from_datetime", "to_datetime"],
        unique=False,
        schema="crawler",
    )
    op.create_table(
        "session_entity_map",
        sa.Column("entity_id", sa.BigInteger(), nullable=False),
        sa.Column("session_id", sa.BigInteger(), nullable=False),
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["entity_id"], ["crawler.entities.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["session_id"], ["crawler.sessions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "entity_id", "session_id", name="uix_entity_session"
        ),
        schema="crawler",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("session_entity_map", schema="crawler")
    op.drop_index(
        "ix_entity_datetime_range",
        table_name="channel_metadata",
        schema="crawler",
    )
    op.drop_table("channel_metadata", schema="crawler")
    op.drop_table("sessions", schema="crawler")
    op.drop_table("entities", schema="crawler")
    # ### end Alembic commands ###
