"""crate tables

Revision ID: afd3993281a3
Revises: e766a37ae352
Create Date: 2025-07-07 15:33:10.352859

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "afd3993281a3"
down_revision: str | None = "e766a37ae352"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "entities",
        sa.Column("entity_id", sa.BigInteger(), nullable=False),
        sa.Column("entity_name", sa.String(), nullable=False),
        sa.Column("entity_url", sa.String(), nullable=False),
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="crawler",
    )
    op.create_table(
        "session",
        sa.Column("session", sa.String(), nullable=False),
        sa.Column("api_id", sa.String(), nullable=False),
        sa.Column("api_hash", sa.String(), nullable=False),
        sa.Column("tel", sa.String(), nullable=False),
        sa.Column("proxy", sa.String(), nullable=False),
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="crawler",
    )
    op.create_table(
        "session_entity_map",
        sa.Column("entity_id", sa.BigInteger(), nullable=False),
        sa.Column("session_id", sa.BigInteger(), nullable=False),
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["entity_id"],
            ["crawler.entities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["crawler.session.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "entity_id", "session_id", name="uix_entity_session"
        ),
        schema="crawler",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("session_entity_map", schema="crawler")
    op.drop_table("session", schema="crawler")
    op.drop_table("entities", schema="crawler")
    # ### end Alembic commands ###
